name: rick
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  gql: 0.13.1-alpha+1645425888336 #DO NOT TOUCH IT WITHOUT IT EVERYTHING FALLS APART
  gql_dio_link: ^0.2.1
  graphql_flutter: ^5.1.1-beta.4
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  artemis: ^7.1.1-beta.1
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed: ^1.0.2+1
  freezed_annotation: ^1.1.0
  path_provider: ^2.0.11
dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
flutter:
   uses-material-design: true
